export const MAX_PLAYERS = 4;

export const ROOM_PHASES = {
  PREPARE: "PREPARE",
  STARTING: "STARTING",
  SUSPEND_PENDING: "SUSPEND_PENDING",
  IN_GAME: "IN_GAME",
  SUSPENDED: "SUSPENDED",
  ABANDONED: "ABANDONED",
  FINISHED: "FINISHED",
  ARCHIVED: "ARCHIVED"
};
